/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programads.pkg17.calculadoraalpha;

import java.awt.CardLayout;
import java.awt.Font;

/**
 *
 * @author arthu_uhkw4r8
 */
public class CalculadoraAlpha extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraAlpha
     */
    private final CardLayout cardLayout;
    
    public CalculadoraAlpha() {
        initComponents();
        
        this.pack();
        this.setLocationRelativeTo(null);
        
        cardLayout = (CardLayout) painelPrincipal.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        painelCalc = new javax.swing.JPanel();
        txtNum1 = new javax.swing.JTextField();
        btnSoma = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnRaiz = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        txtNum2 = new javax.swing.JTextField();
        btnMult = new javax.swing.JButton();
        btnSigno = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtVisor = new javax.swing.JTextArea();

        txtVisor.setVisible(false);
        painelZod = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMes = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDia = new javax.swing.JTextArea();
        btnPrev = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lblMesNas = new javax.swing.JLabel();
        lblDiaNas = new javax.swing.JLabel();
        lblIntro = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextArea();
        txtResultado.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 900));
        setPreferredSize(new java.awt.Dimension(10, 10));
        setSize(new java.awt.Dimension(800, 900));

        painelPrincipal.setBackground(new java.awt.Color(51, 51, 51));
        painelPrincipal.setForeground(new java.awt.Color(51, 51, 51));
        painelPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelPrincipal.setLayout(new java.awt.CardLayout());

        painelCalc.setBackground(new java.awt.Color(51, 51, 51));
        painelCalc.setForeground(new java.awt.Color(51, 51, 51));

        txtNum1.setBackground(new java.awt.Color(51, 51, 51));
        txtNum1.setForeground(new java.awt.Color(255, 255, 255));
        txtNum1.setText("0");
        txtNum1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNum1.setCaretColor(new java.awt.Color(51, 51, 51));
        txtNum1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNum1.setDoubleBuffered(true);
        txtNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNum1ActionPerformed(evt);
            }
        });

        btnSoma.setBackground(new java.awt.Color(51, 51, 51));
        btnSoma.setForeground(new java.awt.Color(255, 255, 255));
        btnSoma.setText("+");
        btnSoma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSoma.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSoma.setDoubleBuffered(true);
        btnSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomaActionPerformed(evt);
            }
        });

        btnDiv.setBackground(new java.awt.Color(51, 51, 51));
        btnDiv.setForeground(new java.awt.Color(255, 255, 255));
        btnDiv.setText("/");
        btnDiv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDiv.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDiv.setDoubleBuffered(true);
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btnRaiz.setBackground(new java.awt.Color(51, 51, 51));
        btnRaiz.setForeground(new java.awt.Color(255, 255, 255));
        btnRaiz.setText("raiz");
        btnRaiz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRaiz.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRaiz.setDoubleBuffered(true);
        btnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizActionPerformed(evt);
            }
        });

        btnSub.setBackground(new java.awt.Color(51, 51, 51));
        btnSub.setForeground(new java.awt.Color(255, 255, 255));
        btnSub.setText("-");
        btnSub.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSub.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSub.setDoubleBuffered(true);
        btnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubActionPerformed(evt);
            }
        });

        txtNum2.setBackground(new java.awt.Color(51, 51, 51));
        txtNum2.setForeground(new java.awt.Color(255, 255, 255));
        txtNum2.setText("0");
        txtNum2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNum2.setCaretColor(new java.awt.Color(51, 51, 51));
        txtNum2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNum2.setDoubleBuffered(true);
        txtNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNum2ActionPerformed(evt);
            }
        });

        btnMult.setBackground(new java.awt.Color(51, 51, 51));
        btnMult.setForeground(new java.awt.Color(255, 255, 255));
        btnMult.setText("x");
        btnMult.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMult.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMult.setDoubleBuffered(true);
        btnMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultActionPerformed(evt);
            }
        });

        btnSigno.setBackground(new java.awt.Color(51, 51, 51));
        btnSigno.setForeground(new java.awt.Color(255, 255, 255));
        btnSigno.setText("Signo");
        btnSigno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSigno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSigno.setDoubleBuffered(true);
        btnSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignoActionPerformed(evt);
            }
        });

        btnClean.setBackground(new java.awt.Color(51, 51, 51));
        btnClean.setForeground(new java.awt.Color(255, 255, 255));
        btnClean.setText("Limpar");
        btnClean.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnClean.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClean.setDoubleBuffered(true);
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        txtVisor.setBackground(new java.awt.Color(51, 51, 51));
        txtVisor.setColumns(20);
        txtVisor.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtVisor.setForeground(new java.awt.Color(255, 255, 255));
        txtVisor.setRows(5);
        txtVisor.setText("0\n");
        txtVisor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtVisor.setCaretColor(new java.awt.Color(51, 51, 51));
        jScrollPane2.setViewportView(txtVisor);

        javax.swing.GroupLayout painelCalcLayout = new javax.swing.GroupLayout(painelCalc);
        painelCalc.setLayout(painelCalcLayout);
        painelCalcLayout.setHorizontalGroup(
            painelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCalcLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelCalcLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(painelCalcLayout.createSequentialGroup()
                        .addGroup(painelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCalcLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSoma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNum1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnSub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(224, 224, 224)
                        .addGroup(painelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCalcLayout.createSequentialGroup()
                                .addComponent(btnMult, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))
                            .addGroup(painelCalcLayout.createSequentialGroup()
                                .addGroup(painelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
        );
        painelCalcLayout.setVerticalGroup(
            painelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCalcLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(painelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(painelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSoma)
                    .addComponent(btnMult)
                    .addComponent(btnSub))
                .addGap(108, 108, 108)
                .addGroup(painelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDiv)
                    .addComponent(btnRaiz)
                    .addComponent(btnSigno))
                .addGap(79, 79, 79)
                .addComponent(btnClean)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        painelPrincipal.add(painelCalc, "painelCalc");
        painelCalc.getAccessibleContext().setAccessibleName("painelCalc");

        painelZod.setForeground(new java.awt.Color(51, 51, 51));
        painelZod.setToolTipText("");

        txtMes.setBackground(new java.awt.Color(255, 255, 255));
        txtMes.setColumns(20);
        txtMes.setForeground(new java.awt.Color(0, 0, 0));
        txtMes.setRows(5);
        jScrollPane1.setViewportView(txtMes);

        txtDia.setBackground(new java.awt.Color(255, 255, 255));
        txtDia.setColumns(20);
        txtDia.setForeground(new java.awt.Color(0, 0, 0));
        txtDia.setRows(5);
        jScrollPane3.setViewportView(txtDia);

        btnPrev.setBackground(new java.awt.Color(51, 51, 51));
        btnPrev.setForeground(new java.awt.Color(255, 255, 255));
        btnPrev.setText("Previsão");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(51, 51, 51));
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblMesNas.setText("Mês de nascimento");

        lblDiaNas.setText("Dia de nascimento");

        lblIntro.setText("Esse programa irá estipular seu signo de acordo com seu dia e mês de nascimento.");
        lblIntro.setFocusable(false);
        lblIntro.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txtResultado.setBackground(new java.awt.Color(255, 255, 255));
        txtResultado.setColumns(20);
        txtResultado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(0, 0, 0));
        txtResultado.setRows(5);

        javax.swing.GroupLayout painelZodLayout = new javax.swing.GroupLayout(painelZod);
        painelZod.setLayout(painelZodLayout);
        painelZodLayout.setHorizontalGroup(
            painelZodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelZodLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelZodLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(lblDiaNas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMesNas)
                .addGap(142, 142, 142))
            .addGroup(painelZodLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrev)
                .addGap(171, 171, 171))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelZodLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIntro, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(painelZodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelZodLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        painelZodLayout.setVerticalGroup(
            painelZodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelZodLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(painelZodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMesNas, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiaNas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelZodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(35, 35, 35)
                .addComponent(lblIntro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addGroup(painelZodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrev)
                    .addComponent(btnVoltar))
                .addGap(286, 286, 286))
            .addGroup(painelZodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelZodLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        painelPrincipal.add(painelZod, "painelZod");
        painelZod.getAccessibleContext().setAccessibleName("painelZod");

        getContentPane().add(painelPrincipal, java.awt.BorderLayout.CENTER);
        painelPrincipal.getAccessibleContext().setAccessibleName("painelPrincipal");
        painelPrincipal.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubActionPerformed
        // TODO add your handling code here:
        try{
            txtNum2.setVisible(true);
            txtVisor.setVisible(true);
            
            double num1 = Double.parseDouble(txtNum1.getText());
            double num2 = Double.parseDouble(txtNum2.getText());
            double sub = num1 > num2? num1 - num2 : num2 - num1;
            txtVisor.setFont(new Font("Arial", Font.PLAIN, 24));
            txtVisor.setText(String.valueOf(sub));
        }catch (NumberFormatException e){
            txtVisor.setFont(new Font("segoe UI", Font.PLAIN, 18));
            txtVisor.setText("Erro: Entrada Inválida");
        }
    }//GEN-LAST:event_btnSubActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        // TODO add your handling code here:
        txtNum2.setVisible(true);
        txtVisor.setVisible(true);
        txtNum2.setText("0");
            
        txtNum1.setText("");
        txtNum2.setText("");
        txtVisor.setText("");
    }//GEN-LAST:event_btnCleanActionPerformed

    private void btnSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignoActionPerformed
        // TODO add your handling code here:
        txtResultado.setVisible(false);
        
        cardLayout.show(painelPrincipal, "painelZod");
        
        this.pack();
    }//GEN-LAST:event_btnSignoActionPerformed

    private void txtNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNum2ActionPerformed

    private void txtNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNum1ActionPerformed

    private void btnSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomaActionPerformed
        // TODO add your handling code here:
        try{
            txtNum2.setVisible(true);
            txtVisor.setVisible(true);
            
            
            double num1 = Double.parseDouble(txtNum1.getText());
            double num2 = Double.parseDouble(txtNum2.getText());
            double soma = num1 + num2;
            
            txtVisor.setFont(new Font("Arial", Font.PLAIN, 24));
            txtVisor.setText(String.valueOf(soma));
        } catch (NumberFormatException e){
            txtVisor.setFont(new Font("segoe UI", Font.PLAIN, 18));
            txtVisor.setText("Erro: Entrada Inválida");
        }
    }//GEN-LAST:event_btnSomaActionPerformed

    private void btnMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultActionPerformed
        // TODO add your handling code here:
         try{
            txtNum2.setVisible(true);
            txtVisor.setVisible(true);
            
            double num1 = Double.parseDouble(txtNum1.getText());
            double num2 = Double.parseDouble(txtNum2.getText());
            double mult = num1 * num2;
            
            txtVisor.setFont(new Font("Arial", Font.PLAIN, 24));
            txtVisor.setText(String.valueOf(mult));
        } catch (NumberFormatException e){
            txtVisor.setFont(new Font("segoe UI", Font.PLAIN, 18));
            txtVisor.setText("Erro: Entrada Inválida");
        }
    }//GEN-LAST:event_btnMultActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        // TODO add your handling code here:
          try{
            txtNum2.setVisible(true);
            txtVisor.setVisible(true);
            
            double num1 = Double.parseDouble(txtNum1.getText());
            double num2 = Double.parseDouble(txtNum2.getText());
            
            if(num1 != 0 && num2 != 0){
                double div = num1 > num2 ? num1/num2 : num2/num1;
                txtVisor.setFont(new Font("Arial", Font.PLAIN, 24));
                txtVisor.setText(String.valueOf(div));
            }else{
                txtVisor.setFont(new Font("segoe UI", Font.PLAIN, 18));
                txtVisor.setText("Erro! Nao foi possivel realizar uma divisao por zero!");
            }
            
        } catch (NumberFormatException e){
            txtVisor.setFont(new Font("segoe UI", Font.PLAIN, 18));
            txtVisor.setText("Erro: Entrada Inválida");
        }
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizActionPerformed
        // TODO add your handling code here:
        try{
            txtVisor.setVisible(true);
            txtNum2.setVisible(false);
            txtNum2.setText("");
            
            double num1 = Double.parseDouble(txtNum1.getText());
            double raiz;
            
            if (num1 < 0){
                txtVisor.setFont(new Font("Arial", Font.PLAIN, 18));
                txtVisor.setText("Erro: Entrada Inválida, não é possível calcular a raiz de um número negativo!");
            }else{
                raiz = Math.sqrt(num1);
                txtVisor.setFont(new Font("Arial", Font.PLAIN, 24));
                txtVisor.setText(String.valueOf(raiz));
            }

        } catch (NumberFormatException e){
            txtVisor.setFont(new Font("segoe UI", Font.PLAIN, 18));
            txtVisor.setText("Erro: Entrada Inválida");
        }
    }//GEN-LAST:event_btnRaizActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        cardLayout.show(painelPrincipal, "painelCalc");
        
        txtDia.setText("");
        txtMes.setText("");
        txtResultado.setText("");
        txtResultado.setVisible(false);
        
        this.pack();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        try{
            int dia = Integer.parseInt(txtDia.getText());
            int mes = Integer.parseInt(txtMes.getText());
            String signo = "Data invalida";
            
            if ((mes == 1 && dia >= 21) || (mes == 2 && dia <= 18)) {
                signo = "Aquário";
            } else if ((mes == 2 && dia >= 19) || (mes == 3 && dia <= 20)) {
                signo = "Peixes";
            } else if ((mes == 3 && dia >= 21) || (mes == 4 && dia <= 20)) {
                signo = "Áries";
            } else if ((mes == 4 && dia >= 21) || (mes == 5 && dia <= 20)) {
                signo = "Touro";
            } else if ((mes == 5 && dia >= 21) || (mes == 6 && dia <= 20)) {
                signo = "Gêmeos";
            } else if ((mes == 6 && dia >= 21) || (mes == 7 && dia <= 22)) {
                signo = "Câncer";
            } else if ((mes == 7 && dia >= 23) || (mes == 8 && dia <= 22)) {
                signo = "Leão";
            } else if ((mes == 8 && dia >= 23) || (mes == 9 && dia <= 22)) {
                signo = "Virgem";
            } else if ((mes == 9 && dia >= 23) || (mes == 10 && dia <= 22)) {
                signo = "Libra";
            } else if ((mes == 10 && dia >= 23) || (mes == 11 && dia <= 21)) {
                signo = "Escorpião";
            } else if ((mes == 11 && dia >= 22) || (mes == 12 && dia <= 21)) {
                signo = "Sagitário";
            } else if ((mes == 12 && dia >= 22) || (mes == 1 && dia <= 20)) {
                signo = "Capricórnio";
            }
            
            txtResultado.setFont(new Font("Arial", Font.PLAIN, 18));
            txtResultado.setText("Seu signo é: " + signo);
        }catch (NumberFormatException e){
            txtResultado.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
            txtResultado.setText("ERRO: Por favor, insira o Dia e o Mês como números válidos.");
        }
       
        
        txtResultado.setVisible(true);
    }//GEN-LAST:event_btnPrevActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraAlpha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraAlpha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraAlpha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraAlpha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraAlpha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnMult;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnRaiz;
    private javax.swing.JButton btnSigno;
    private javax.swing.JButton btnSoma;
    private javax.swing.JButton btnSub;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDiaNas;
    private javax.swing.JLabel lblIntro;
    private javax.swing.JLabel lblMesNas;
    private javax.swing.JPanel painelCalc;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel painelZod;
    private javax.swing.JTextArea txtDia;
    private javax.swing.JTextArea txtMes;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum2;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextArea txtVisor;
    // End of variables declaration//GEN-END:variables
}
